### ISSUE TITLE
alf->ulf license activation no longer possible for personal licenses

### ISSUE THREAD

**Issue by RedGlow** [game-ci/documentation#408]
**Bug description**

The documentation (in [Converting into a license](https://game.ci/docs/github/activation#converting-into-a-license)) instructs to go to https://license.unity3d.com in order to activate a personal license.

The website, though, provides activation procedures only for Pro licenses now:
![image](https://github.com/game-ci/documentation/assets/238052/e82a919b-0529-4ebb-8e44-b65cab34b5a5)

The linked documentation doesn't really seem to offer any useful information.

**Steps to reproduce**

- Go to https://license.unity3d.com/manual
- Upload an ULF file
- Try to activate it with a personal license serial number
- Get an error from the website

**Comment by webbertakken** [comment]
Thank you for your bug report.

Related to https://github.com/game-ci/unity-request-activation-file/issues/97.

A solution is being discussed on [our discord](https://game.ci/discord) in [Unity License Activation](https://discord.com/channels/710946343828455455/1138586951604248666) topic.

**Comment by anatawa12** [comment]
It looks workaround described in #415 is no longer working.
I could not find `<div class="option option-personal clear" style="display: none;">` in the HTML

**Comment by GabLeRoux** [comment]
@anatawa12 I just confirmed that the workaround still works.

<img width="1792" alt="ScreenShot Safari 2023-09-10 at 22 16 42@2x" src="https://github.com/game-ci/documentation/assets/1264761/884b7b39-7090-4cdc-9f8c-70289faa4443">

<img width="1792" alt="ScreenShot Safari 2023-09-10 at 22 16 54@2x" src="https://github.com/game-ci/documentation/assets/1264761/6dbd509a-d25d-4f3d-97da-855b7359dc90">

I was able to download an activated license file for a personal license.

**Comment by anatawa12** [comment]
Sorry, I was looking for the element in the first page just after uploading alf, not `Activate your license` page. I confirmed the workaround is working. Thank you.

**Comment by GabLeRoux** [comment]
No problem, thanks for contributing to the docs, much appreciated! 🙌

**Comment by Tuntenfisch** [comment]
Hello, I've just tried the workaround and am getting an "Invalid access token" error.

![image](https://github.com/game-ci/documentation/assets/11965324/90c37b8b-b724-41f0-8c62-745fb8b76ffb)

**Comment by GabLeRoux** [comment]
I confirm it still works. 

![ScreenShot Safari 2023-09-18 at 08 47 03](https://github.com/game-ci/documentation/assets/1264761/4eaf3a2b-d108-492c-bc0d-542aac03fd01)

The error you're seeing is probably related to your user session on Unity's website. Try logging out and logging in again.

**Comment by gautaz** [comment]
Hello,

I just tried to generate a license file on https://license.unity3d.com but I don't seem to have the opportunity to select anything related to the "Unity Personal Edition" during the process, here is a capture of the page rendered by my browser:

![image](https://github.com/game-ci/documentation/assets/11046232/fe7c199f-f29d-4722-bb58-9b364f99a055)

I have no idea what I did wrong so any help is welcome.

**Comment by GabLeRoux** [comment]
Just confirmed that the workaround is still working

![ScreenShot Safari 2023-09-26 at 10 30 10@2x](https://github.com/game-ci/documentation/assets/1264761/eaa354d8-cc9b-402c-8125-be395767f522)

**Comment by gautaz** [comment]
Hello @GabLeRoux, thanks for your time, I've tried again and this time I found the "undisplayed" `div`.
I must have looked at the wrong place in the DOM the first time I tried.
My apologies for the hassle.

**Comment by GabLeRoux** [comment]
No worries, glad you got it working 🙌

**Comment by aw042** [comment]
I can't seem to get it working. I tried my best to find the correct element to alter, but I think they've changed their site. The page now displays "Unity no longer supports manual activation of Personal licenses."
![image](https://github.com/game-ci/documentation/assets/50641350/e504e445-c7ca-4f38-8b6d-3c31cf32ed35)

Here is the html I am seeing now:
![image](https://github.com/game-ci/documentation/assets/50641350/d212f159-0c68-4894-ac60-8ce89a6a878e)

**Comment by GabLeRoux** [comment]
It's in the second step after uploading the file

**Comment by luuuuyang** [comment]
The personal license needs to be returned in UnityHub first!

**Comment by iije** [comment]
Hi. How do I obtain the alt/ilf file to be use for the upload to get to the second step.

**Comment by MidoriaEMM** [comment]
it didn't work cause the reason mentioned that "**serial has reached the maximum number of activations**", i wonder if UNITY has changed that and is there anyone got the same issue?

**Comment by flonou** [comment]
I've had issues getting the licence file too that I solved by adding the following command line parameter to the unity editor call :
`-createManualActivationFile`

**Comment by MidoriaEMM** [comment]
> it didn't work cause the reason mentioned that "**serial has reached the maximum number of activations**", i wonder if UNITY has changed that and is there anyone got the same issue?

in my case that i can get the .alf file from docker image but when i tried to get personal lisense then i got the error **"serial has reached the maximum number of activations"**, I wonder if it is that i have multiple personal lisenses on many PCs that i can't find a way to return them all so there are many references on UNITY's server that cause the issue.

**Comment by MidoriaEMM** [comment]
> > it didn't work cause the reason mentioned that "**serial has reached the maximum number of activations**", i wonder if UNITY has changed that and is there anyone got the same issue?
> 
> in my case that i can get the .alf file from docker image but when i tried to get personal license then i got the error **"serial has reached the maximum number of activations"**, I wonder if it is that i have multiple personal licenses on many PCs that i can't find a way to return them all so there are many references on UNITY's server that cause the issue.

Done. Just like what i think, the solution is to regsiter a new unity account to make sure there is no other references on the UNITY's server.(**Don't forget to clear the cookie when switch the account**)

**Comment by mixxit** [comment]
To complete activation, you must import the license file to the Unity product you will use on the offline device

This seems to have gone 

![image](https://github.com/game-ci/documentation/assets/233287/41b958a3-bcae-4e08-a9da-db3b7f5bc76b)

**Comment by MaZhengKe** [comment]
Even if I modify the Html element and click the button, the result still fails.
![image](https://github.com/game-ci/documentation/assets/30165889/36439a12-5774-4bed-b958-821ed0d7b28a)
![image](https://github.com/game-ci/documentation/assets/30165889/fe661b27-93b2-46a5-86d0-7ef1a1e9138e)

**Comment by Cardidi** [comment]
> Even if I modify the Html element and click the button, the result still fails. ![image](https://private-user-images.githubusercontent.com/30165889/316754201-36439a12-5774-4bed-b958-821ed0d7b28a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTE2MjAsIm5iZiI6MTcxMjkxMTMyMCwicGF0aCI6Ii8zMDE2NTg4OS8zMTY3NTQyMDEtMzY0MzlhMTItNTc3NC00YmVkLWI5NTgtODIxZWQwZDdiMjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA4NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNWIyYTZkNjRjNmY0NWZiODgyNzA1MGYyOGIwNmMyODkyMzBiNDQyODMyODViYTI3YWEyMjEwYmEyN2JlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhV6pHBA8TwZc3MDMG7EIUujMNKYMN73E9gM0BKubS0) ![image](https://private-user-images.githubusercontent.com/30165889/316754277-fe661b27-93b2-46a5-86d0-7ef1a1e9138e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTE2MjAsIm5iZiI6MTcxMjkxMTMyMCwicGF0aCI6Ii8zMDE2NTg4OS8zMTY3NTQyNzctZmU2NjFiMjctOTNiMi00NmE1LTg2ZDAtN2VmMWExZTkxMzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA4NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNjI5MDNiMmM3ZmFmM2VhNjZiNTZhODg5ZTkzMmY0ZDM0NWFkMzNjMjMxMTZhMzM1NjkzMWMxYzIxYjA4ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EN8WADeDVBd8vKcihF4V6UlowD_nNKB44RoDqwYQDPI)

Me either

**Comment by Cardidi** [comment]
> > Even if I modify the Html element and click the button, the result still fails. ![image](https://private-user-images.githubusercontent.com/30165889/316754201-36439a12-5774-4bed-b958-821ed0d7b28a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTE2MjAsIm5iZiI6MTcxMjkxMTMyMCwicGF0aCI6Ii8zMDE2NTg4OS8zMTY3NTQyMDEtMzY0MzlhMTItNTc3NC00YmVkLWI5NTgtODIxZWQwZDdiMjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA4NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNWIyYTZkNjRjNmY0NWZiODgyNzA1MGYyOGIwNmMyODkyMzBiNDQyODMyODViYTI3YWEyMjEwYmEyN2JlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhV6pHBA8TwZc3MDMG7EIUujMNKYMN73E9gM0BKubS0) ![image](https://private-user-images.githubusercontent.com/30165889/316754277-fe661b27-93b2-46a5-86d0-7ef1a1e9138e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTE2MjAsIm5iZiI6MTcxMjkxMTMyMCwicGF0aCI6Ii8zMDE2NTg4OS8zMTY3NTQyNzctZmU2NjFiMjctOTNiMi00NmE1LTg2ZDAtN2VmMWExZTkxMzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA4NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNjI5MDNiMmM3ZmFmM2VhNjZiNTZhODg5ZTkzMmY0ZDM0NWFkMzNjMjMxMTZhMzM1NjkzMWMxYzIxYjA4ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EN8WADeDVBd8vKcihF4V6UlowD_nNKB44RoDqwYQDPI)
> 
> Me either

I fix this via register a new Unity ID...

**Comment by Modsgvccgh** [comment]
> > Just confirmed that the workaround is still working
> > ![ScreenShot Safari 2023-09-26 at 10 30 10@2x](https://private-user-images.githubusercontent.com/1264761/270691545-eaa354d8-cc9b-402c-8125-be395767f522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTQyMTgsIm5iZiI6MTcxNjI5MzkxOCwicGF0aCI6Ii8xMjY0NzYxLzI3MDY5MTU0NS1lYWEzNTRkOC1jYzliLTQwMmMtODEyNS1iZTM5NTc2N2Y1MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMTIxODM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGMyZjkwODljODRmNjg0MDMyYTBkZWRiYTdiZGI2MjM1NTYwNTA4ZWRmNTJjZTI5ODVhNjgzOWVmM2I1M2YwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FeHXuoGpIWhDQkzQzCF3ZjQnBj0kbzb_nT0TXQiCpa4)
> 
> I cant see the same structure of page, if here some trick to enable options div? <img alt="image" width="1680" src="https://private-user-images.githubusercontent.com/84394557/332421840-cd1dd084-6f96-43fa-895b-a35b151a8b09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzYzNTQsIm5iZiI6MTcxODIzNjA1NCwicGF0aCI6Ii84NDM5NDU1Ny8zMzI0MjE4NDAtY2QxZGQwODQtNmY5Ni00M2ZhLTg5NWItYTM1YjE1MWE4YjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDIzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNDhlN2I5MWE2YTlhOGU4NGM3YzEyZWNkZjcxNTRmZjI1NDk4YTQ3ZWQ4MzU3OTFmODAyNjBiMGZjZTMwNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Si4_OqyR7dGrdB-WBHVYm98NNh5QsUeKEAKf-KNYcmk">

you need to be on the second step

**Comment by strongDong** [comment]
> @anatawa12我刚刚确认该解决方法仍然有效。
> 
> <img alt="Safari 截图 2023-09-10 22 16 42@2x" width="1792" src="https://private-user-images.githubusercontent.com/1264761/266891050-884b7b39-7090-4cdc-9f8c-70289faa4443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzcwMDEsIm5iZiI6MTcyMzUzNjcwMSwicGF0aCI6Ii8xMjY0NzYxLzI2Njg5MTA1MC04ODRiN2IzOS03MDkwLTRjZGMtOWY4Yy03MDI4OWZhYTQ0NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDgxMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I2MjJiNjBmZWJkNGIzODJjMWMwZWUyMjcxYmI0MGI1NGIxOTYwODVhY2FiMjg4Yzg4YjJkYzUwYTQ0YjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UJ_Nz1y6TKzrM7nDptbpR8R6Ivav4XyfINW8JfPTceQ"> <img alt="Safari 截图 2023-09-10 22 16 54@2x" width="1792" src="https://private-user-images.githubusercontent.com/1264761/266891080-6dbd509a-d25d-4f3d-97da-855b7359dc90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzcwMDEsIm5iZiI6MTcyMzUzNjcwMSwicGF0aCI6Ii8xMjY0NzYxLzI2Njg5MTA4MC02ZGJkNTA5YS1kMjVkLTRmM2QtOTdkYS04NTViNzM1OWRjOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDgxMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQ4NjFmNjA3ZmQzNjYwZmYyN2U5NTI3M2Y1ODc2MDRiZDBmZmRkNGM2MDZhZjYzMGZkOWY2MGU1ODE4N2FkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ggxCJiPlcem8gSzMevIAzmYJDsf0NGSU5SFLq8P62UA">
> 我刚才能够下载个人许可证的激活文件。

This method is no longer effective.
![image](https://github.com/user-attachments/assets/37b88c08-ad1c-471e-979e-f3b608b6dd70)

**Comment by eliphatfs** [comment]
Same here. serial cannot be FREE type.

**Comment by 0x9be00ff1** [comment]
This method is no longer effective.
"serial serial can not be FREE type."

**Comment by nitpum** [comment]
> @anatawa12 I just confirmed that the workaround still works.
> <img alt="ScreenShot Safari 2023-09-10 at 22 16 42@2x" width="1792" src="https://private-user-images.githubusercontent.com/1264761/266891050-884b7b39-7090-4cdc-9f8c-70289faa4443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDMxNjEsIm5iZiI6MTcyODc0Mjg2MSwicGF0aCI6Ii8xMjY0NzYxLzI2Njg5MTA1MC04ODRiN2IzOS03MDkwLTRjZGMtOWY4Yy03MDI4OWZhYTQ0NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMTQyMTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmI3YzM0OGZhOGU3NTVhYjJmNmE5Yzk5ZjE5YThlMjkwNDlhOTY5NWE1MzI5MDEwYTAxMTUxNmYyOTE0ZDE0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YIXNLEfxXSMCL7Q6X-O9LiqqUaOVBPsfIdWXRKn61uA"> <img alt="ScreenShot Safari 2023-09-10 at 22 16 54@2x" width="1792" src="https://private-user-images.githubusercontent.com/1264761/266891080-6dbd509a-d25d-4f3d-97da-855b7359dc90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDMxNjEsIm5iZiI6MTcyODc0Mjg2MSwicGF0aCI6Ii8xMjY0NzYxLzI2Njg5MTA4MC02ZGJkNTA5YS1kMjVkLTRmM2QtOTdkYS04NTViNzM1OWRjOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMTQyMTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUzZmVjMTUzMDBmZGFiNmFlYTRhMjQ0OGYyNTg5NTkzODg3OWU5Mjk2ZWJhNmNmMjE4NzkzMWZhOGUwZTY5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.D1l99SDB0yeiPxD5ht4_L_bWxqtGvv3inBsiHJoIbks">
> 
> I was able to download an activated license file for a personal license just now.

This method still work

**Comment by dncry** [comment]
> @anatawa12 I just confirmed that the workaround still works.
> <img alt="ScreenShot Safari 2023-09-10 at 22 16 42@2x" width="1792" src="https://private-user-images.githubusercontent.com/1264761/266891050-884b7b39-7090-4cdc-9f8c-70289faa4443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTgxMDYsIm5iZiI6MTcyODk1NzgwNiwicGF0aCI6Ii8xMjY0NzYxLzI2Njg5MTA1MC04ODRiN2IzOS03MDkwLTRjZGMtOWY4Yy03MDI4OWZhYTQ0NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMDIwMzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI0MDlmZjYwMjZmZWU5NWQwNTkxZGNjYzExMDdkOTM2ZmQ4NzYzZTEyYWNlNTMzOTljYWE0NTQyMTM1M2FlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2X0Co5dAMEzqi4Hps7cuuCV1uJYHcgjQmdxpQhwW9cg"> <img alt="ScreenShot Safari 2023-09-10 at 22 16 54@2x" width="1792" src="https://private-user-images.githubusercontent.com/1264761/266891080-6dbd509a-d25d-4f3d-97da-855b7359dc90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTgxMDYsIm5iZiI6MTcyODk1NzgwNiwicGF0aCI6Ii8xMjY0NzYxLzI2Njg5MTA4MC02ZGJkNTA5YS1kMjVkLTRmM2QtOTdkYS04NTViNzM1OWRjOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMDIwMzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2RlMDQ2MGJhMjE5YWM2OTY4ZTdlM2E0ZGI4MDlkNzQ3OWI5OTc2NTUzODg1MjkyYzZlN2Q5M2JiOGFmYmMyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JHrHNMEK30BEZZNuY0ddx5ID-1GkYh2M7p7_Lt7FxFk">
> 
> I was able to download an activated license file for a personal license just now.

not work  . error : "serial serial can not be FREE type."

**Comment by AndreasStgm** [comment]
Can confirm that the workaround on the website still works.

**Comment by juhanikarlsson** [comment]
I can't get it to work even with the workaround. I wonder if it's because the claim of the personal license is so old (2016?) :' )

**Comment by webbertakken** [comment]
> I can't get it to work even with the workaround. I wonder if it's because the claim of the personal license is so old (2016?) :' )

Basically every 2 months there's someone confirming that it still works - so for most people it does. 

Would be nice to find out when it doesn't and where you get stuck exactly - with details/screenshot perhaps. Could you please elaborate @juhanikarlsson

**Comment by MathiusD** [comment]
Yes, I can confirm that the solution works for my runners (I used it today).

**Comment by kamangir** [comment]
Worked! Thank you! 😁

**Comment by DNAniel213** [comment]
same. It's no longer possible here

**Comment by MathiusD** [comment]
No issue on my side.
I've used the free licence activation just right now (like depicted here) and that the solution works for my gitlab runners.

**Comment by AlianBlank** [comment]
I have tried to register with a new account. Also unable to obtain authorization

<img width="1850" height="1665" alt="Image" src="https://github.com/user-attachments/assets/b6cd2492-5d34-4597-867f-62525e2b34ad" />

<img width="1734" height="1578" alt="Image" src="https://github.com/user-attachments/assets/1e2d26f8-4a33-4196-8ed3-b3dc5770c632" />

**Comment by AlianBlank** [comment]
> Online activation still works, no issues.在线激活仍然有效，没有问题。 Generate alf file, upload it, on second "license" page find element with "option option-personal clear" class and delete it's style.生成 alf 文件，上传它，在第二个“license”页面找到具有 "option option-personal clear" 类的元素并删除其 style。 Select **"I have less than100k$ in this year"** option.选择“今年收入低于 100k$”选项。 **You must not have pro subscription** on your account, otherwise, create separate account for free edition.您必须没有专业订阅，否则，请为免费版创建一个单独的账户。

I have tried to register with a new account. Also unable to obtain authorization.
Do you have any other way to obtain authorization?

**Comment by GabLeRoux** [comment]
You don’t actually need to rely on the manual activation website anymore.  
(**I just confirmed that the process still works as of 2025-08-21, but it’s not the recommended way.**)  

<details><summary>Proof manual activation still works</summary>
<p>

*This is just for reference. The Unity Hub method below is simpler and future-proof.*

1. Create a ULF file from unity cli

```bash
/Applications/Unity/Hub/Editor/6000.0.34f1/Unity.app/Contents/MacOS/Unity \
  -batchmode \
  -quit \
  -createManualActivationFile \
  -logfile -
```

```
Unity Editor version:    6000.0.34f1 (xxxxxxxxxxxx)
Branch:                  6000.0/staging
Build type:              Release
Batch mode:              YES
macOS version:           Version 15.6 (Build 24G84)
Darwin version:          24.6.0
Architecture:            arm64
Running under Rosetta:   NO
Available memory:        131072 MB

[Licensing::Module] Trying to connect to existing licensing client channel...
[Licensing::IpcConnector] Connection attempt to the License Client on channel: "LicenseClient-USER" failed because channel doesn't exist; code: "0x80000002"
Launching external process: /Applications/Unity/Hub/Editor/6000.0.34f1/Unity.app/Contents/Frameworks/UnityLicensingClient.app/Contents/MacOS/Unity.Licensing.Client
[Licensing::Module] Successfully launched the LicensingClient (PId: 11110)
[Licensing::Client] Error: Code 1 while verifying Licensing Client signature (process Id: 11110, path: "/Applications/Unity/Hub/Editor/6000.0.34f1/Unity.app/Contents/Frameworks/UnityLicensingClient.app/Contents/MacOS/Unity.Licensing.Client")
[Licensing::Module] Error: LicensingClient has failed validation; ignoring
[Licensing::Client] Handshaking with LicensingClient:
  Version:                 1.16.2+xxxxxxx
  Session Id:              [REDACTED]
  Correlation Id:          [REDACTED]
  External correlation Id: [REDACTED]
  Machine Id:              [REDACTED]
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-USER" (connect: 0.27s, validation: 0.03s, handshake: 0.02s)
[Licensing::IpcConnector] Successfully connected to the License Notification on channel: "LicenseClient-USER-notifications" at "2025-08-21T15:03:19.180315Z"
[Licensing::Module] Connected to LicensingClient (PId: 11110, launch time: 0.00, total connection time: 0.32s)
[Licensing::Module] Error: Access token is unavailable; failed to update
[Licensing::Client] Error: Code 500 while processing request (status: Unable to update licenses. Errors: No ULF license found.,Token not found in cache)
[Licensing::Client] Error: Code 500 while updating license in client (status: Unable to update licenses. Errors: No ULF license found.,Token not found in cache)
[Licensing::Module] Generating manual activation license file: /Users/USERNAME/Unity_v6000.0.34f1.alf
[Licensing::Client] Successfully processed ALF generation request: /Users/USERNAME/Unity_v6000.0.34f1.alf
[Licensing::Module] Manual activation license file successfully saved.
```

2. Then I upload `Unity_v6000.0.34f1.alf` to https://license.unity3d.com/manual and a green checkmark appears

<img width="1796" height="1162" alt="Image" src="https://github.com/user-attachments/assets/27c971aa-d8ae-43a1-aa02-714d667746a6" />

3. I hit next
4. I see a page asking me for a Serial Number:

<img width="1818" height="1072" alt="Image" src="https://github.com/user-attachments/assets/16781420-3e39-4fa4-a940-925502488881" />
 
5. I right click on page, show inspector and look for the following:

<img width="1130" height="308" alt="Image" src="https://github.com/user-attachments/assets/700a9f6b-4248-452d-91bd-e9ac7f64c264" />

6. I remove that `display: none` hardcoded style and the form appears

<img width="1848" height="2054" alt="Image" src="https://github.com/user-attachments/assets/c4b81546-0529-4a21-ae46-cfa70f285a91" />

![hackerman](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnJmbWY5MDEwMzc3aGR5dTdkbXpub2Zvczk1a2IybTE3YWRrcDhnMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ieBWQkIVEELhbizGAp/giphy.gif)

I select free and continue.

<img width="2084" height="1568" alt="Image" src="https://github.com/user-attachments/assets/6ffc3ee2-9848-4cf3-a35b-5b6e68889701" />

Voilà, _Download license file_, you now have a `ULF` file ready to use. :v:

_⚠️ Manual activation still works for now, but it’s brittle and might stop anytime._

</p>
</details> 

Instead, you can **bypass this entirely by extracting a serial from a local activation done with Unity Hub**:

### How it works

* Open **Unity Hub** → Preferences → Licenses → Add.  
* **Click Add even if you already see a license listed** (this ensures a fresh activation).  
* Once activated, the `.ulf` file on your machine contains the license details.  
* From that `.ulf` file, you can **extract the serial**.

### Why this helps

* That serial is **not tied to the Machine ID**.
* You can pass it directly when invoking Unity from the CLI, for example:

```bash
unity \
  -username <USERNAME> \
  -password <PASSWORD> \
  -serial <SERIAL>
```

### In CI (e.g. GitHub Actions / GitLab CI)

* GameCI’s Unity Builder (GitHub Actions) will automatically extract the serial from the `.ulf` file. That is why you can use the content of the ulf directly in `UNITY_LICENSE` env var.
* If you ever need to run Unity manually (outside the builder), you can reuse the same extracted serial.
* The extraction process is documented here:
  👉 **[GitLab CI Docs – Extracting the Serial from a `.ulf` file](https://game.ci/docs/gitlab/activation)**

**Comment by hugebug4ever** [comment]
the web method is expired with error from server

<img width="1058" height="143" alt="Image" src="https://github.com/user-attachments/assets/94c85fe8-017b-4a67-a4d6-0b64f3450480" />

while it's confirmed the manual activation still works.

**Comment by Yeet-Masta** [comment]
> You don’t actually need to rely on the manual activation website anymore. (**I just confirmed that the process still works as of 2025-08-21, but it’s not the recommended way.**)
> Proof manual activation still works
> 
> 
> 
> 
> 
> 
> Instead, you can **bypass this entirely by extracting a serial from a local activation done with Unity Hub**:
> ### How it works
> 
>     * Open **Unity Hub** → Preferences → Licenses → Add.
> 
>     * **Click Add even if you already see a license listed** (this ensures a fresh activation).
> 
>     * Once activated, the `.ulf` file on your machine contains the license details.
> 
>     * From that `.ulf` file, you can **extract the serial**.
> 
> 
> ### Why this helps
> 
>     * That serial is **not tied to the Machine ID**.
> 
>     * You can pass it directly when invoking Unity from the CLI, for example:
> 
> 
> unity \
>   -username <USERNAME> \
>   -password <PASSWORD> \
>   -serial <SERIAL>
> 
> ### In CI (e.g. GitHub Actions / GitLab CI)
> 
>     * GameCI’s Unity Builder (GitHub Actions) will automatically extract the serial from the `.ulf` file. That is why you can use the content of the ulf directly in `UNITY_LICENSE` env var.
> 
>     * If you ever need to run Unity manually (outside the builder), you can reuse the same extracted serial.
> 
>     * The extraction process is documented here:
>       👉 **[GitLab CI Docs – Extracting the Serial from a `.ulf` file](https://game.ci/docs/gitlab/activation)**
> 
> 
> In short:
> 
> > Extract your Unity serial from the .ulf file:
> > This command decodes the internal DeveloperData field to reveal the serial used for activation (even for Personal).
> > On macOS or Linux:
> > cat Unity_lic.ulf | grep DeveloperData | sed -E 's/.*Value="([^"]+)".*/\1/' | base64 --decode
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On Windows using Powershell:
> > Get-Content Unity_lic.ulf | Select-String -Pattern 'DeveloperData' | ForEach-Object { $_ -replace '.*Value="([^"]+)".*', '$1' } | [System.Convert]::FromBase64String($_)
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Expected Serial Format
> > The serial should look like this: XX-XXXX-XXXX-XXXX-XXXX-XXXX.

This powershell command throws an error on later versions use this instead:
Get-Content Unity_v4.x.ulf | Select-String -Pattern 'DeveloperData' | ForEach-Object { 
    $base64 = $_ -replace '.*Value="([^"]+)".*', '$1'
    $bytes = [System.Convert]::FromBase64String($base64)
    [System.Text.Encoding]::UTF8.GetString($bytes)
}

**Comment by crowbait** [comment]
> This powershell command throws an error on later versions use this instead: Get-Content Unity_v4.x.ulf | Select-String -Pattern 'DeveloperData' | ForEach-Object { $base64 = $_ -replace '._Value="([^"]+)"._', '$1' $bytes = [System.Convert]::FromBase64String($base64) [System.Text.Encoding]::UTF8.GetString($bytes) }

In my case, I had to adapt the Regex to actually replace everything not-base64 by expanding `.` to `.*`:
```powershell
Get-Content Unity_lic.ulf | Select-String -Pattern 'DeveloperData' | ForEach-Object {
  $base64 = $_ -replace '.*Value="([^"]+)".*', '$1'
  $bytes = [System.Convert]::FromBase64String($base64)
  [System.Text.Encoding]::UTF8.GetString($bytes)
}
```
